
-- Nadia's Perfume Cart: announcements + secure admin policy
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  text_ar text not null,
  text_en text not null,
  link text default 'shop.html',
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.announcements enable row level security;

drop policy if exists "public can read active announcements" on public.announcements;
create policy "public can read active announcements"
on public.announcements for select
to anon, authenticated
using (is_active = true);

drop policy if exists "admins can manage announcements" on public.announcements;
create policy "admins can manage announcements"
on public.announcements for all
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.announcements (text_ar,text_en,link,is_active)
select 'الجديد الحصري من Nadia’s Perfume Cart','Exclusive news from Nadia’s Perfume Cart','shop.html',true
where not exists (select 1 from public.announcements);
